# Site settings
title: heroydx Blog
SEOTitle: 东晓的博客 | heroydx Blog
header-img: img/post-bg-desk.jpg
email: yangdongxiao666@gmail.com
description: "分享是一个好习惯"
keyword: "heroydx, heroydx Blog, 东晓的博客, yangdongxiao, 杨东晓, Arduino, Python"
url: "http://heroydx.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/heroydx/heroydx.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "自闭桃源称太古，欲栽大木柱长天。"
sidebar-avatar: /img/about-ydx-puppy.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     18531520655
# zhihu_username:     qiubaiying
github_username:    heroydx
facebook_username:  yangdongxiao
# jianshu_username:   e71990ada2fd
twitter_username:   ydx1208




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: afecc82758c43fdcabc6   #生成的clientID
  clientSecret: 4013cca2bece4c1b7886b2b27e362d50022b07cc  #同上
  repo: issue    #仓库名称
  owner: heroydx    #github用户名
  admin: ['heroydx']
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
  id: 'window.location.pathname' #页面的唯一标识，gitalk 会根据这个标识自动创建的issue的标签,我们使用页面的相对路径作为标识


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-113879948-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "BY",
        href: "http://wwwhttp://qiubaiying.top/"
    },{
        title: "Arduino",
        href: "https://www.arduino.cc/"
    },{
        title: "Python",
        href: "https://www.python.org/"
    }
]
